deployment:
  tasks:
    - export NODE_ENV=production
    - /opt/cpanel/ea-nodejs18/bin/npm install
    - /opt/cpanel/ea-nodejs18/bin/npm run build
    - /bin/cp -r dist/* /home/your_cpanel_user/public_html/
